import type { RemoteHub } from './remote';

/**
 * Everything the Worker is handed at runtime.
 *
 * Generated by `wrangler types` in most projects; written by hand here because
 * the bindings are few and one of them (PHOTOS) is deliberately optional —
 * R2 is not enabled on the account yet and the booth has to run without it.
 */
export interface Env {
  /** Metadata, settings, sessions — and photo bytes too, until R2 exists. */
  DB: D1Database;
  /** Photo, frame and QR bytes. Absent until R2 is switched on. */
  PHOTOS?: R2Bucket;
  /** The kiosk <-> phone hub. */
  REMOTE: DurableObjectNamespace<RemoteHub>;
  /** The built SPA in dist/. */
  ASSETS: Fetcher;

  /** Overrides the origin baked into QR codes. Rarely needed now: unlike the
   *  tunnel, a Worker already knows its own public hostname. */
  PUBLIC_URL?: string;
  PHOTO_TTL_DAYS?: string;
  BOOTH_PASSWORD?: string;
  DOWNLOAD_PASSWORD?: string;
}
